name: Setup
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: |
          pyproject.toml
          uv.lock
    - uses: actions/cache@v4
      with:
        path: .uv
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
    - uses: astral-sh/setup-uv@v3
      with:
        version: latest
    - run: uv sync --dev
      shell: bash
