repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies: [mdformat-gfm]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest -q
        language: system
        pass_filenames: false
      - id: build-docs
        name: build docs
        entry: make docs
        language: system
        pass_filenames: false
      - id: check-registry
        name: check tribunal registry
        entry: python scripts/check_tribunal_registry.py
        language: system
        pass_filenames: false
      - id: dbt-parse
        name: dbt parse
        entry: dbt parse --project-dir dbt
        language: system # Assumes dbt is installed in the environment
        types: [sql, yaml] # Run on changes to .sql or .yml files in models/seeds/etc.
        files: ^dbt/ # Only run if files in dbt/ directory change
        pass_filenames: false
