version: '3.9'
services:
  app:
    build: .
    environment:
      - TRIBUNAL=${TRIBUNAL:-tjro}
    volumes:
      - .:/app
      - ./data:/app/data
    command: bash
  analytics:
    build: .
    environment:
      - TRIBUNAL=${TRIBUNAL:-tjro}
    volumes:
      - .:/app
      - ./data:/app/data
    command: python scripts/run_analytics.py
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
