[project]
name = "causa-ganha"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.173.0",
    "google-auth>=2.40.3",
    "google-generativeai>=0.8.5",
    "mkdocs>=1.6.1",
    "pandas>=2.3.0",
    "python-json-logger>=3.3.0",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
