name: 01 - Daily PDF Collection

on:
  schedule:
    - cron: '0 5 * * *' # Runs at 05:00 UTC daily
  workflow_dispatch: # Allows manual triggering

jobs:
  collect_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Get current date
        id: date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Run downloader script (latest)
        run: |
          uv run python causaganha/core/downloader.py --latest

      - name: Upload downloaded PDF
        uses: actions/upload-artifact@v4
        with:
          name: diario-pdf-${{ steps.date.outputs.TODAY }}
          path: causaganha/data/diarios/dj_*.pdf
          if-no-files-found: error # Fail the workflow if the PDF is not found
