name: Legacy IA Archive (Standalone)

on:
  workflow_dispatch:
    inputs:
      max_items:
        description: 'Maximum items to process'
        required: false
        type: string
        default: '10'
      start_date:
        description: 'Start date (YYYY-MM-DD)'
        required: false
        type: string
      end_date:
        description: 'End date (YYYY-MM-DD)'
        required: false
        type: string

env:
  IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
  IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
  MAX_CONCURRENT_DOWNLOADS: 2
  MAX_CONCURRENT_IA_UPLOADS: 1

jobs:
  legacy-archive:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python and dependencies
        uses: ./.github/actions/setup

      - name: Legacy Archive Process
        run: |
          echo "🚀 Running legacy archive process..."
          
          # Build command for async pipeline
          CMD="uv run python src/async_diario_pipeline.py --verbose"
          
          if [ -n "${{ inputs.max_items }}" ]; then
            CMD="$CMD --max-items ${{ inputs.max_items }}"
          fi
          
          if [ -n "${{ inputs.start_date }}" ]; then
            CMD="$CMD --start-date ${{ inputs.start_date }}"
          fi
          
          if [ -n "${{ inputs.end_date }}" ]; then
            CMD="$CMD --end-date ${{ inputs.end_date }}"
          fi
          
          echo "Executing: $CMD"
          eval $CMD

      - name: Archive Summary
        if: always()
        run: |
          echo "📊 Archive Statistics:"
          uv run python src/async_diario_pipeline.py --stats-only || echo "No progress data found"

      - name: Upload Progress
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: legacy-archive-${{ github.run_id }}
          path: |
            data/diario_pipeline_progress.json
          retention-days: 3
          if-no-files-found: ignore