name: 03 - Update Elo Ratings

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["02 - PDF Content Extraction"]
    types:
      - completed

jobs:
  update:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "/root/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Run pipeline
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          DATE=$(date +'%Y-%m-%d')
          python causaganha/core/pipeline.py run --date $DATE

      - name: Commit updated ratings
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add causaganha/data/ratings.csv causaganha/data/partidas.csv
          if git diff --cached --quiet; then
            echo "No CSV changes to commit"
          else
            git commit -m "Update Elo ratings" && git push
          fi
