name: Analytics Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/setup
      - name: Run analytics pipeline
        run: python scripts/run_analytics.py
      - name: Run tests
        run: uv run pytest -q
