name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "/root/.cargo/bin" >> $GITHUB_PATH
        shell: bash
      - name: Install dependencies
        run: uv pip install --system -r requirements.txt
      - name: Run tests
        run: pytest -q
