name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install dependencies
        run: |
          uv sync --dev
          uv pip install -e .
      - name: Format and lint code
        run: |
          uv run ruff format
          uv run ruff check --fix
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git commit -am "chore(ci): auto-fix linting"
            git push
          fi
      - name: Run tests
        run: uv run pytest tests/ --cov=src --cov-report=xml
      - name: Build documentation
        run: make docs
