name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/setup
      - name: Format and lint code
        run: |
          uv run ruff format
          uv run ruff check --fix
      - name: Run pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git commit -am "chore(ci): auto-fix linting"
            git push
          fi
  tribunal-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tribunal: [tjro]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-tests
        with:
          tribunal: ${{ matrix.tribunal }}
  docs:
    needs: tribunal-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build documentation
        run: make docs
